
@host=polydictor.eastus.cloudapp.azure.com
//@host=localhost:8081

###
GET http://{{host}}/get-market-analysis
#?marketId=693941
?marketId=665374
&days=7
&limit=100000

###
GET http://{{host}}/get-market-analysis
#?marketId=693941
?marketId=665374
&days=1
&limit=2


###
GET http://localhost:8081/tracked

###
POST http://localhost:8081/tracked
?url=https://polymarket.com/event/will-the-us-invade-iran-before-2027
#?url=https://polymarket.com/event/which-companies-announce-bankruptcy-before-2027/will-beyond-meat-announce-bankruptcy-before-2027-859-613-462-581-119
