
###
GET http://localhost:8081/get-market-analysis
?marketId=665374
&days=7
&limit=100000


###
GET http://localhost:8081/tracked

###
POST http://localhost:8081/tracked
#?url=https://polymarket.com/event/will-the-us-invade-iran-before-2027
?url=https://polymarket.com/event/which-companies-announce-bankruptcy-before-2027/will-beyond-meat-announce-bankruptcy-before-2027-859-613-462-581-119
